### PR TITLE
add requirements and update readme

### PR DESCRIPTION
**Pull request by Lewington-pitsos**
I can confirm that after installing the `requirements.txt` the example code from the readme runs without issue on Ubuntu 22.04.

this repo is really cool, I'm just testing it out at the moment but there's anything else that I can help with please let me know.

### CODE REVIEW

**Comment by norabelrose** [comment]
Hmm I'd prefer not to duplicate the list of requirements, since they are already included in the `pyproject.toml`. I'll update the README to make it clear that you can `pip install` the library once you've cloned it to get the required libraries.

And I plan to get rid of the hard Triton dependency today

**Comment by AmanPriyanshu** [comment]
Had a query regarding `triton` dependency as well and whether it would be removed in the future

**Comment by AmanPriyanshu** [comment]
Was able to install `triton` in Mac through the following steps - for reference till dependency is removed:

```
git clone git@github.com:triton-lang/triton.git;
cd triton/python;
pip install ninja cmake wheel;
pip install .
```

Allowed installation of `sae`

**Comment by norabelrose** [comment]
> Was able to install `triton` in Mac through the following steps - for reference till dependency is removed:
> 
> ```
> git clone git@github.com:triton-lang/triton.git;
> cd triton/python;
> pip install ninja cmake wheel;
> pip install .
> ```
> 
> Allowed installation of `sae`

Oh cool. For now you can at least use other parts of `sae` without triton since I moved the import statement inside `decode` itself. I'll close this PR once we have full out-of-the-box Mac support.

**Comment by norabelrose** [comment]
Triton dependency removed in fdde64c

**Pull request closed without merging**
